config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :blogs
  resources :services
  resources :areas
  devise_for :admins

  root 'pages#home'
  get 'dashboard' => 'dashboard#show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ActiveRecord::Base
  mount_uploader :area_picture, AreaPictureUploader
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  mount_uploader :blog_picture, BlogPictureUploader
  include Bootsy::Container
end

app/models/service.rb
class Service < ActiveRecord::Base
  mount_uploader :service_picture, ServicePictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :destroy, :update]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:city, :heading1, :body1, :heading2, :body2, :information, :area_picture)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :heading, :body, :blog_picture, :bootsy_image_gallery_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :heading1, :body1, :heading2, :body2, :information, :service_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :heading1 %><br>
    <%= f.text_field :heading1, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body1 %><br>
    <%= f.text_area :body1, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :heading2 %><br>
    <%= f.text_field :heading2, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body2 %><br>
    <%= f.text_area :body2, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :information %><br>
    <%= f.text_area :information, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Area_Picture %><br>
    <%= f.file_field :area_picture %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">

<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

  </div>
</div>

app/views/areas/index.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">
    <p id="notice"><%= notice %></p>
      </br>
      <h1>Areas We Serve</h1>
      </br>
      </br>
        <div>
          <% @areas.each do |area| %>
              <div><p style="text-transform: capitalize; font-size: 16px;"><%= area.city %></p></div>
              <div style="font-size:14px; margin-top: 5px;"><i><%= link_to "See what services we offer in #{area.city}", area %></i></div>
              <hr>
          <% end %>
        </div>

      <br>

      <% if current_admin.present? %> 
      <%= link_to 'New Area', new_area_path %>
      <% end %>
  </div>
</div>

app/views/areas/new.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">

<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

  </div>
</div>

app/views/areas/show.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">
  </br>
    <p id="notice"><%= notice %></p>

      <h1>
        <%= @area.city %>
      </h1>

      <div>
        <%= image_tag @area.area_picture.url(:medium).to_s %>
      </div>

      <h2>
        <%= @area.heading1 %>
      </h2>

      <p>
        <%= @area.body1 %>
      </p>

      <h2>
        <%= @area.heading2 %>
      </h2>

      <p>
        <%= @area.body2 %>
      </p>

      <p>
        <%= @area.information %>
      </p>

      <% if current_admin.present? %>
      <p>
        <%= link_to 'Destroy', @area, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <%= link_to 'Edit', edit_area_path(@area) %> |
        <%= link_to 'New Area', new_area_path %>
      </p>
      <% end %>

    </br>
    </br>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :heading %><br>
    <%= f.text_field :heading, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.bootsy_area :body, class:"form-control", rows: "25" %>
  </div>
  <div class="form-group">
    <%= f.label :Blog_Picture %><br>
    <%= f.file_field :blog_picture %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">

<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

  </div>
</div>

app/views/blogs/index.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">
    <p id="notice"><%= notice %></p>
      </br>
      <h1 style="text-align:center">USA Electrical Systems Blog</h1>
      </br>
      </br>
        <div>
          <% @blogs.each do |blog| %>
              <div style="font-size:18px"><%= link_to "#{blog.title}", blog %></div>
              </br>
              <div style="font-size:16px;"><i><%= blog.heading %></i></div>
            <hr>
          <% end %>
        </div>

      <br>

    <div style="text-align:right">
    <% if current_admin.present? %>
      <%= link_to 'New Blog Post', new_blog_path %>
    <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">

</br>

<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

  </div>
</div>

app/views/blogs/show.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">

    <p id="notice"><%= notice %></p>

    </br>
    <h1>
      <%= @blog.title %>
    </h1>
    </br>
    <hr>
    <div>
      <%= image_tag @blog.blog_picture.url(:medium).to_s %>
    </div>
    </br>
    <h4>
      <%= @blog.heading %>
    </h4>
    </br>
    <p>
      <%= simple_format(@blog.body) %>
    <p>

     <% if current_admin.present? %>
    <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Edit', edit_blog_path(@blog) %> 
    |     <% end %>
      <%= link_to 'Back', blogs_path %>
  </div>
</div>

app/views/dashboard/show.html.erb
This is your dashboard
<%= link_to 'New Area', new_area_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsaelectricalsystemsTemp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

   <nav class="navbar navbar-inverse" id="navtainer" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand">USA Electrical Systems</a>
        </div>
       
        <div class="navbar-container-right">
          
          <ul class="nav nav-pills navbar-right">
              <li>
                <%= link_to 'Home', root_path %>
              </li>
              <li>
                <%= link_to 'Service Areas', areas_path %>
              </li>
              <li>
                <%= link_to 'Services', services_path %>
              </li>
              <li>
                <%= link_to 'Blog', blogs_path %>
              </li>

              <% if current_admin.present? %>
              <li>  
                  <%= link_to 'Dashboard', 'dashboard' %>
              </li>
              <li>
                  <%= link_to 'Sign Out',destroy_admin_session_path, :method => :delete %>
              </li>
              <% end %>
              
          </ul>

        </div>
      </div><!-- /.container-fluid -->
    </nav>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid">
    
  <div class="row banner">
    <div class="slogan">
      <h1 style="font-weight:900; font-size:65px; text-shadow: 5px 5px black;">Welcome to USA Electrical Systems</h1>
      </br>
      <h2 style="text-shadow: 2px 2px black;"><i>The leading provider of electrical services for the greater Los Angeles Area</i></h2>
    </br>
    <a class="btn btn-primary btn-lg" href="#" role="button" style="padding-left:50px; padding-right:50px; color: white;">Learn More</a>
    </div>
  </div>

</div>

<div class="contrainer">


  <div class="services">
    <h1>Services</h1>
      </br>
      </br>
      </br>
      <div class="row">
        <div class="col-sm-6" style="text-align:left; padding-left:100px; padding-right:50px;">
          <h3>Residential</h3>
          </br>
          <p>If you are looking to install lighting in your home or simply need some troubleshooting give us a call, 
            we are experts in all things residential. We have worked with thousands of residential clients and know how get the job done</p>
          </br>
          <ul>
            <li>Lighting Control Systems</li>
            <li>Rewiring</li>
            <li>Kitchen Lighting</li>
            <li>Bathroom Lighting</li>
            <li>Landscape Lighting</li>
            <li>Energy Efficient LED Lighting</li>
            <li>Service Meter Upgrades</li>
            <li>Troubleshooting</li>
            <li>... And Much More!</li>
          </ul>
        </div>
        <div class="col-sm-6" style="font-size: 55px; color: #f0ad4e">
          <i class="fa fa-5x fa-building"></i>
        </div>
      </div>
      </br>
      </br>
      <hr>
      </br>
      </br>
      </br>

      <div class="row">
        <div class="col-sm-6" style="font-size: 55px; color: #5bc0de;">
          <i class="fa fa-5x fa-briefcase"></i>
        </div>
        <div class="col-sm-6" style="text-align:left; padding-left:100px; padding-right:50px;">
          <h3>Commercial</h3>
          </br>
          <p>We are an approved lighting control technician employer. We can fulltill all your needs with Title24 or any commercial work.</p>
          </br>
          <ul>
            <li>CALCTP(acceptance technicans on site)</li>
            <li>Tenant Improvements</li>
            <li>Code Compliance - CA Title 24</li>
            <li>Apartment & Commercial Building Repairs</li>
            <li>Troubleshooting</li>
            <li>... And Much More!</li>
          </ul>
        </div>
      </div>
      </br>
      </br>
      </br>
      <hr>
      </br>
      </br>

      <div class="row">
        <div class="col-sm-6" style="text-align:left; padding-left:100px; padding-right:50px;">
          <h3>Industrial</h3>
          </br>
          <p>Whether it's a motor control center or a machine shop installation we can help you with your industrial needs.</p>
          </br>
          <ul>
            <li>Motor Controls</li>
            <li>Machinery(Machine Shops)</li>
            <li>Pumps</li>
            <li>Air Compressor</li>
            <li>... And Much More!</li>
          </ul>
        </div>
        </br>
        <div class="col-md-6" style="font-size: 55px; color: #5cb85c;">
          <i class="fa fa-5x fa-wrench"></i>
        </div>  
      </div>
   


  </br>
  </br>
  </br>
  <hr> 
  <div class="row areas">
    <h1>Areas We Serve</h1>
    </br>
    </br>
    </br>
    <div class="col-sm-4">
        <p><i class="fa fa-map-marker"></i> Agoura, CA</p>
        <p><i class="fa fa-map-marker"></i> Arcadia, CA</p>
        <p><i class="fa fa-map-marker"></i> Anaheim, CA</p>
        <p><i class="fa fa-map-marker"></i> Chatsworth, CA</p>
        <p><i class="fa fa-map-marker"></i> Calabasas, CA</p>
        <p><i class="fa fa-map-marker"></i> Canoga Park, CA</p>
    </div>
    <div class="col-sm-4">
        <p><i class="fa fa-map-marker"></i> Culver City, CA</p>
        <p><i class="fa fa-map-marker"></i> Glendale, CA</p>
        <p><i class="fa fa-map-marker"></i> Hermosa Beach, CA</p>
        <p><i class="fa fa-map-marker"></i> Hollywood, CA</p>
        <p><i class="fa fa-map-marker"></i> Inglewood, CA</p>
        <p><i class="fa fa-map-marker"></i> Los Angeles, CA</p>
    </div>
    <div class="col-sm-4">
        <p><i class="fa fa-map-marker"></i> Santa Monica, CA</p>
        <p><i class="fa fa-map-marker"></i> Moorpark, CA</p>
        <p><i class="fa fa-map-marker"></i> Long Beach, CA</p>
        <p><i class="fa fa-map-marker"></i> Malibu, CA</p>
        <p><i class="fa fa-map-marker"></i> Woodland Hills, CA</p>
        <p><i class="fa fa-map-marker"></i> Northridge, CA</p>
    </div>
  </div>
  <hr>
  <div class="row contact">
    <h1>Contact</h1>
    </br>
    </br>
    <p>Rey Noris</p>
    <p>7655 Winnetka Ave Ste 3103</p>
    <p>Winnetka, CA 91306 Winnetka</p>
    <p>(818) 427-4767</p>
  </div>

</div>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :heading1 %><br>
    <%= f.text_field :heading1, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body1 %><br>
    <%= f.text_area :body1, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :heading2 %><br>
    <%= f.text_field :heading2, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body2 %><br>
    <%= f.text_area :body2, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :information %><br>
    <%= f.text_area :information, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Service_Picture %><br>
    <%= f.file_field :service_picture %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">

<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

  </div>
</div>

app/views/services/index.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">
    <p id="notice"><%= notice %></p>
      </br>
      <h1 style="text-align:center">USA Electrical Systems Services</h1>
      </br>
      </br>
        <div>
          <% unless @services.empty? %>
          <% @services.each do |service| %>
              <div style="font-size:18px"><%= link_to "#{service.title}", service %></div>
              </br>
              <div style="font-size:16px;"><i><%= service.heading1 %></i></div>
            <hr>
          <% end %>
          <% end %>
        </div>

      <br>

    <div style="text-align:right">
    <% if current_admin.present? %>
      <%= link_to 'New Service', new_service_path %>
    <% end %>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<div class="container-fluid">
  <div class="col-sm-4 col-sm-offset-4">

<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

  </div>
</div>

app/views/services/show.html.erb
<div class="container-fluid">
  <div class="col-sm-6 col-sm-offset-3">
    <p id="notice"><%= notice %></p>

      </br>
      </br>
      <h1>
        <%= @service.title %>
      </h1>

      <hr>

      <div>
        <%= image_tag @service.service_picture.url(:medium).to_s %>
      </div>

      <h2>
        <%= @service.heading1 %>
      </h2>

      <p>
        <%= @service.body1 %>
      </p>

      <h2>
        <%= @service.heading2 %>
      </h2>

      <p>
        <%= @service.body2 %>
      </p>

      <p>
        <%= @service.information %>
      </p>

      <% if current_admin.present? %>
      <%= link_to 'Destroy', @service, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Edit', edit_service_path(@service) %> |
      <%= link_to 'Back', services_path %>
      <% end %>

  </div>
</div>